# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := glframework imgui lodepng Bouncer

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

glframework: 
	@echo "==== Building glframework ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f glframework.make

imgui: 
	@echo "==== Building imgui ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f imgui.make

lodepng: 
	@echo "==== Building lodepng ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f lodepng.make

Bouncer: glframework imgui
	@echo "==== Building Bouncer ($(config)) ===="
	@${MAKE} --no-print-directory -C build -f Bouncer.make

clean:
	@${MAKE} --no-print-directory -C build -f glframework.make clean
	@${MAKE} --no-print-directory -C build -f imgui.make clean
	@${MAKE} --no-print-directory -C build -f lodepng.make clean
	@${MAKE} --no-print-directory -C build -f Bouncer.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   glframework"
	@echo "   imgui"
	@echo "   lodepng"
	@echo "   Bouncer"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
